import { Repo } from "../components/RepoList";

export const additionRepos: Repo[] = [
    {
        name: "Services",
        shortDescriptionHTML: "",
        url: "https://services.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "Whetstone",
        shortDescriptionHTML: "",
        url: "https://whetstone.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "software" } }] },
    },
    {
        name: "Nodepad",
        shortDescriptionHTML: "",
        url: "https://nodepad.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "software" } }] },
    },
    {
        name: "Pravdomil Piano",
        shortDescriptionHTML: "",
        url: "https://piano.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "design" } }] },
    },
    {
        name: "Přijímačky UMPRUM",
        shortDescriptionHTML: "",
        url: "https://prijimackyumprum.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "czech" } }] },
    },
    {
        name: "halftone-workshop",
        shortDescriptionHTML: "",
        url: "https://halftone-workshop.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "workshop" } }] },
    },
    {
        name: "cmyk-workshop",
        shortDescriptionHTML: "",
        url: "https://cmyk-workshop.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "workshop" } }] },
    },
    {
        name: "prawood",
        shortDescriptionHTML: "",
        url: "https://prawood.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "photography",
        shortDescriptionHTML: "",
        url: "https://www.icloud.com/sharedalbum/#B0P5oqs3qkAGn;30709E02-4714-4CEA-B4DE-17C88DB668FC",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "graphics-design",
        shortDescriptionHTML: "",
        url: "https://graphic.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "web-development",
        shortDescriptionHTML: "",
        url: "https://web.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "3d-print",
        shortDescriptionHTML: "",
        url: "https://3dprint.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "sound",
        shortDescriptionHTML: "",
        url: "https://sound.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "Viewfinder",
        shortDescriptionHTML: "",
        url: "https://viewfinder.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "mobile-apps" } }] },
    },
    {
        name: "nodragreleasedelay",
        shortDescriptionHTML: "",
        url: "https://nodragreleasedelay.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "jailbreak",
        shortDescriptionHTML: "",
        url: "https://jailbreak.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "programming",
        shortDescriptionHTML: "",
        url: "https://programming.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "wordpress",
        shortDescriptionHTML: "",
        url: "https://wordpress.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "magiclantern",
        shortDescriptionHTML: "",
        url: "https://magiclantern.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "learn",
        shortDescriptionHTML: "",
        url: "https://learn.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "yearprogress",
        shortDescriptionHTML: "",
        url: "https://yearprogress.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "newton-law",
        shortDescriptionHTML: "",
        url: "https://newton-law.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "bookletflow",
        shortDescriptionHTML: "",
        url: "https://bookletflow.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "fusion",
        shortDescriptionHTML: "",
        url: "https://fusion.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "cheatsheet",
        shortDescriptionHTML: "",
        url: "https://cheatsheet.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "electronic",
        shortDescriptionHTML: "",
        url: "https://electronic.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "papercut",
        shortDescriptionHTML: "",
        url: "https://papercut.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "pravidla-typografie",
        shortDescriptionHTML: "",
        url: "https://pravidla-typografie.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "heroes3rady",
        shortDescriptionHTML: "",
        url: "https://heroes3rady.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "pravidla-grafiky",
        shortDescriptionHTML: "",
        url: "https://pravidla-grafiky.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "mackeyboardpiano",
        shortDescriptionHTML: "",
        url: "https://mackeyboardpiano.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "macos",
        shortDescriptionHTML: "",
        url: "https://macos.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
];
