import { Repo } from "../components/RepoList";

export const additionalRepos: Repo[] = [
    {
        name: "Services",
        description: "",
        url: "",
        homepageUrl: "https://services.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    
    
    {
        name: "Whetstone",
        description: "Image processing application for macOS with no UI",
        url: "",
        homepageUrl: "https://whetstone.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "applications" } }] },
    },
    {
        name: "Nodepad",
        description: "Another developer tool",
        url: "",
        homepageUrl: "https://nodepad.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "applications" } }] },
    },
    {
        name: "papercut",
        description: "Video editor concept",
        url: "",
        homepageUrl: "https://papercut.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "applications" } }] },
    },
    {
        name: "mackeyboardpiano",
        description: "Use your Mac keyboard as piano keys",
        url: "",
        homepageUrl: "https://mackeyboardpiano.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "applications" } }] },
    },
    {
        name: "yearprogress",
        description: "Progress bar you'd rather see go slower",
        url: "",
        homepageUrl: "https://yearprogress.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "applications" } }] },
    },
    
    
    {
        name: "Pravdomil Piano",
        description: "My piano in development",
        url: "",
        homepageUrl: "https://piano.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "design" } }] },
    },
    {
        name: "Přijímačky UMPRUM",
        description: "Má první kniha",
        url: "",
        homepageUrl: "https://prijimackyumprum.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "czech" } }] },
    },
    {
        name: "prawood",
        description: "",
        url: "",
        homepageUrl: "https://prawood.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "photography",
        description: "",
        url: "",
        homepageUrl: "https://www.icloud.com/sharedalbum/#B0P5oqs3qkAGn;30709E02-4714-4CEA-B4DE-17C88DB668FC",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "graphics-design",
        description: "",
        url: "",
        homepageUrl: "https://graphic.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "web-development",
        description: "",
        url: "",
        homepageUrl: "https://web.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "3d-print",
        description: "",
        url: "",
        homepageUrl: "https://3dprint.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "sound",
        description: "",
        url: "",
        homepageUrl: "https://sound.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "programming",
        description: "",
        url: "",
        homepageUrl: "https://programming.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "wordpress",
        description: "",
        url: "",
        homepageUrl: "https://wordpress.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "magiclantern",
        description: "",
        url: "",
        homepageUrl: "https://magiclantern.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "learn",
        description: "",
        url: "",
        homepageUrl: "https://learn.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "newton-law",
        description: "",
        url: "",
        homepageUrl: "https://newton-law.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "bookletflow",
        description: "",
        url: "",
        homepageUrl: "https://bookletflow.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "cheatsheet",
        description: "",
        url: "",
        homepageUrl: "https://cheatsheet.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "electronic",
        description: "",
        url: "",
        homepageUrl: "https://electronic.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
    {
        name: "pravidla-typografie",
        description: "Doporučené typografické minimum",
        url: "",
        homepageUrl: "https://pravidla-typografie.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "czech" } }] },
    },
    {
        name: "heroes3rady",
        description: "Aneb co jsem slyšel v putice",
        url: "",
        homepageUrl: "https://heroes3rady.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "czech" } }] },
    },
    {
        name: "pravidla-grafiky",
        description: "Shrnutí základů grafického designu",
        url: "",
        homepageUrl: "https://pravidla-grafiky.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [{ topic: { name: "czech" } }] },
    },
    {
        name: "macos",
        description: "",
        url: "",
        homepageUrl: "https://macos.pravdomil.com",
        viewerHasStarred: false,
        stargazers: { totalCount: 0 },
        repositoryTopics: { nodes: [] },
    },
];
